version: 2

project_name: snowflake-mcp

release:
  prerelease: auto
  make_latest: false
  target_commitish: "{{ .Commit }}"

builds:
  - id: snowflake-mcp
    main: .
    binary: snowflake-mcp
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - snowflake-mcp
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - Readme.md

checksum:
  name_template: checksums.txt
