# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnowflakeMcp < Formula
  desc "Local MCP server for querying Snowflake"
  homepage "https://github.com/oxplot/snowflake-mcp"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.0.0/snowflake-mcp_darwin_x86_64.tar.gz"
      sha256 "412798096041b24b8abf0c590065461eb03717bde5bd5a1a614a4f64c1a602d6"

      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.0.0/snowflake-mcp_darwin_arm64.tar.gz"
      sha256 "2d045a28aef5d7695f53d201bb35e7e409af28bb41e308416ea8a77612ba95ea"

      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.0.0/snowflake-mcp_linux_x86_64.tar.gz"
      sha256 "51e96e87fd7c0111bc60c99a83cb2812bc86bb0a16c3bbfdae03c0069102fb0e"
      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.0.0/snowflake-mcp_linux_arm64.tar.gz"
      sha256 "5bd7d7303314a66edef6edccbcc375c6cd46528e402945b3c4265546ba9c06f9"
      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Register with Codex:
        codex mcp add snowflake -- snowflake-mcp
    EOS
  end

  test do
    system "#{bin}/snowflake-mcp", "--version"
  end
end
