# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SnowflakeMcp < Formula
  desc "Local MCP server for querying Snowflake"
  homepage "https://github.com/oxplot/snowflake-mcp"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.1.0/snowflake-mcp_darwin_x86_64.tar.gz"
      sha256 "b875aab6575482e76791c24d0be0497162df8fb7cbf92bcfd253eb888a0b10a4"

      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.1.0/snowflake-mcp_darwin_arm64.tar.gz"
      sha256 "ed099c29805bd13ce6cf1e631b36582bb475c43b3f0faa0a343c3bf456b24e9b"

      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.1.0/snowflake-mcp_linux_x86_64.tar.gz"
      sha256 "17fe6679be52d28762c334ea0af199094a3561b5a290ffa9a74847913a01b85a"
      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oxplot/snowflake-mcp/releases/download/v1.1.0/snowflake-mcp_linux_arm64.tar.gz"
      sha256 "8d92386648d6490ae2382586ea8e5b6e1ec69dcc07992e7d3d37b06cf08a309c"
      define_method(:install) do
        bin.install "snowflake-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      Register with Codex:
        codex mcp add snowflake -- snowflake-mcp
    EOS
  end

  test do
    system "#{bin}/snowflake-mcp", "--version"
  end
end
